<?php echo $this->doctype();
$siteName               =       Application\Controller\ConstantController::SITE_NAME;
$seperator              =       Application\Controller\ConstantController::SEPERATOR;
$siteDescription        =       Application\Controller\ConstantController::SITE_DESCRIPTION;

?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($siteName .$seperator. $this->translate($siteDescription))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/plugins/metisMenu/metisMenu.min.css'))
                        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome-4.1.0/css/font-awesome.min.css'))
                        ?>
    </head>
    <body>
        
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                   <?php echo $this->content; ?>
                        </div>
                    </div>
         
        </div> <!-- /container -->
                <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/jquery-1.11.0.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/plugins/metisMenu/metisMenu.min.js'))
            ->appendFile($this->basePath('js/sb-admin-2.js'))
            ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
